import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
          <html lang="en">
            <body className="bg-gray-50 min-h-screen">
                <header className="border-b bg-white shadow-sm">
                  <nav className="max-w-6xl mx-auto flex items-center justify-between py-6 px-8">
                    <a href="/" className="font-bold text-2xl tracking-tight hover:text-blue-700 transition">portfolio</a>
                    <div className="flex gap-10 text-lg">
                      <a href="/about" className="hover:text-blue-600 font-small">ABOUT ME</a>
                      <a href="/projects" className="hover:text-blue-600 font-small">PROJECTS</a>
                    </div>
                  </nav>
                </header>
              <main className="max-w-6xl mx-auto px-8 py-10">
                {children}
              </main>
            </body>
          </html>
  );
}
